"""Adiciona coluna unidade_medida na tabela Produto

Revision ID: 231e86bfc6e1
Revises: 
Create Date: 2024-08-14 01:44:43.846082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231e86bfc6e1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('produto', sa.Column('unidade_medida', sa.String(length=10), nullable=False, server_default='unidade'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('unidade_medida')

    # ### end Alembic commands ###
