"""Adiciona coluna peso

Revision ID: 585d151e5547
Revises: 231e86bfc6e1
Create Date: 2024-08-14 01:55:01.024332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585d151e5547'
down_revision = '231e86bfc6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('peso')

    with op.batch_alter_table('item_transacao', schema=None) as batch_op:
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
