"""atualizar

Revision ID: c60eb13ae74c
Revises: 585d151e5547
Create Date: 2024-08-14 02:36:48.396022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60eb13ae74c'
down_revision = '585d151e5547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_transacao', schema=None) as batch_op:
        batch_op.drop_column('peso')

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('unidade_medida')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('unidade_medida', sa.VARCHAR(length=10), server_default=sa.text("'unidade'"), nullable=False))

    with op.batch_alter_table('item_transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
